
version: "3.3"
services:
    mariadb:
        build: ./mariadb
        container_name: mariadb
        expose:
            - '3306'
        volumes:
            - /home/zamazzal/data/inception_database:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
        restart: always
        networks:
        - inception
    wordpress:
        build: ./wordpress
        container_name: wordpress
        expose:
            - '9000'
        volumes:
            - /home/zamazzal/data/inception_website:/var/www/wordpress
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
            - WORDPRESS_DB_HOST=mariadb
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
            - WORDPRESS_AUTHOR_USER=${WORDPRESS_AUTHOR_USER}
            - WORDPRESS_ADMIN_PASS=${WORDPRESS_ADMIN_PASS}
            - WORDPRESS_ADMIN_MAIL=${WORDPRESS_ADMIN_MAIL}
            - WORDPRESS_AUTHOR_MAIL=${WORDPRESS_AUTHOR_MAIL}
            - WORDPRESS_AUTHOR_PASS=${WORDPRESS_AUTHOR_PASS}
            - DOMAIN_NAME=${DOMAIN_NAME}
            - WORDPRESS_REDIS_HOST=${WORDPRESS_REDIS_HOST}
        depends_on:
            - mariadb
        restart: always
        networks:
            - inception
    nginx:
        build: ./nginx
        container_name: nginx
        ports:
            - '443:443'
        volumes:
            - /home/zamazzal/data/inception_certifs:/etc/nginx/certifs
            - /home/zamazzal/data/inception_website:/var/www/wordpress
            - /home/zamazzal/data/bonus/adminer:/var/www/adminer
        environment:
            - DOMAIN_NAME=${DOMAIN_NAME}
            - ADMINER_DOMAIN_NAME=${ADMINER_DOMAIN_NAME}
            - STATICWEB_DOMAIN_NAME=${STATICWEB_DOMAIN_NAME}
            - CERTS=${CERTS}
            - CERTS_KEY=${CERTS_KEY}
        depends_on:
            - wordpress
        restart: always
        networks:
        - inception

    ftpserver:
        build: ./bonus/FTPServer
        container_name: ftpserver
        ports:
            - '21:21'
        volumes:
            - /home/zamazzal/data/inception_website:/home/wordpress
        environment:
            - FTP_USER=${FTP_USER}
            - FTP_PASSWORD=${FTP_PASSWORD}
        depends_on:
            - wordpress
        restart: always

    redis:
        build: ./bonus/redis
        container_name: redis
        expose:
            - "6379"
        restart: always
        networks:
        - inception

    adminer:
        build: ./bonus/adminer
        container_name: adminer
        expose:
            - '9001'
        volumes:
            - /home/zamazzal/data/bonus/adminer:/var/www/adminer
        depends_on:
            - mariadb
        restart: always
        networks:
            - inception

    gitwatch:
        build: ./bonus/gitwatch
        container_name: gitwatch
        volumes:
            - /home/zamazzal/data/inception_website:/var/www/wordpress
        environment:
            - GIT_REMOTE=${GIT_REMOTE}
            - GIT_BRANCH=${GIT_BRANCH}
            - GIT_AUTHOR=${GIT_AUTHOR}
        depends_on:
            - wordpress
        restart: always

    staticweb:
        build: ./bonus/staticweb
        container_name: staticweb
        expose:
            - "3000"
        restart: always
        networks:
            - inception

networks:
  inception:
