
version: "3.3"
services:
    mariadb:
        build: ./mariadb
        container_name: mariadb
        expose:
            - '3306'
        volumes:
            - /home/zamazzal/data/inception_database:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
        restart: always
        networks:
        - backend
    wordpress:
        build: ./wordpress
        container_name: wordpress
        expose:
            - '9000'
        volumes:
            - /home/zamazzal/data/inception_website:/var/www/wordpress
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
            - WORDPRESS_DB_HOST=mariadb
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        depends_on:
            - mariadb
        restart: always
        networks:
            - backend
    nginx:
        build: ./nginx
        container_name: nginx
        ports:
            - '443:443'
        volumes:
            - /home/zamazzal/data/inception_certifs:/etc/nginx/certifs
            - /home/zamazzal/data/inception_website:/var/www/wordpress
        environment:
            - DOMAIN_NAME=${DOMAIN_NAME}
            - CERTS=${CERTS}
            - CERTS_KEY=${CERTS_KEY}
        depends_on:
            - wordpress
        restart: always
        networks:
        - backend

networks:
  backend:
